apiVersion: v1
kind: Service
metadata:
  name: dotnetbasicapi
  namespace: dotnetbasicapi
spec:
  type: LoadBalancer
  selector:
    app: dotnetbasicapi
  ports:
    - name: http
      port: 6060
      protocol: TCP
      targetPort: http